# This is a sample Jupyter Notebook

Below is an example of a code cell. 
Put your cursor into the cell and press Shift+Enter to execute it and select the next one, or click 'Run Cell' button.

Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.

To learn more about Jupyter Notebooks in PyCharm, see [help](https://www.jetbrains.com/help/pycharm/ipython-notebook-support.html).
For an overview of PyCharm, go to Help -> Learn IDE features or refer to [our documentation](https://www.jetbrains.com/help/pycharm/getting-started.html).

In [27]:
import numpy as np
"""'#numpy is short for numrrsicsal pythoo used in field which needs heavy fata filing for example numpy array arre faster than normal array list
# eg we can use vectorised operations : np.array ([1,2,3])*2=[2,4,6]]

my_list = [1, 2, 3,4]
print(np.__version__)
print(my_list)
mt=my_list * 2
print(mt)
array1 = np.array([1,2,3,4])
print(array1.ndim)
arr = np.array([[['A','B','C'],['D','E','F'],['G','H','I']],
                [['J','K','L'],['M','N','O'],['P','Q','R']],
                [['S','T','U'],['V','W','X'],['Y','Z',' ']]])

print(arr.ndim)
print(arr.shape)
print(arr[0,1,0])

word =  arr[0,1,2]+arr[2,0,2]+arr[0,0,2]+arr[1,0,1]+arr[2,2,2]+arr[2,0,2]
print(word)
# slicing
slicing = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]])
#array[syar:end:step]
print(slicing[0])
print("h")
print (slicing[0:3])
print("h")
print(slicing[::3],"\n")
print(slicing[::-2],"\n")#prints in reverse order
#for the row selection in each row we need column and it cant be  null
print(slicing[:, ::-1],"\n")
print (slicing[0:2,0:2],"print")
print("hello")

#arethmetic
#scalar arethmetics
print("arith")
arith=np.array([1.32,2.43,3.43])
print(arith+2)
print(arith-2)
print(arith-3)
print(arith/4)
print(arith**5,'\n')
#vectorized math function
print(np.sqrt(arith))
print(np.round(arith))
#for round up
print(np.ceil(arith))
# for round dowm
print(np.floor(arith))
print(np.pi)
"""
#exercises
#the calculation to calculate of a cirlce is A=pi*r**2
"""radi = np.array([1,2,3])
print(np.pi * radi ** 2)"""
# elements wise arithmetic
'''array1 = np.array([1,2,3])
aray2 = np.array([4,5,6])
print(array1 + aray2)
print(array1 - aray2)
print(array1 * aray2)
print(array1 / aray2)
print(array1 ** aray2)'''
#compsrision operator
"""scores = np.array([90,43,432,444,234,232])
print(scores)"""
#broadcasting
#allows numpy to perform operstions on arrays
#with diffrent shapes by virtually expandong dimensions
#so they match the larger array's shape

#dimension have the smae size
#or
#one of he dimensions has a size of 1
"""arr1 = np.array([[1,2,3,4]])
arr2 = np.array([[1],[2],[3],[4]])
print(arr1.shape)
print(arr2.shape)
print("h")
print(arr1*arr2)"""
#operands cant be saped with mismatched numbers
#eg :
#arr1 = np.array([[1,2,3,4],
 #                [5,6,7,8]])
#arr2 = np.array([[1],[2],[3],[4]])
# it is an (2,4)(4,1) eihter they should be matching or one of them should be one
"""arr1 = np.array([[1,2,3,4,5,6,7,8,9,10]])
arr2 = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])
print(arr1*arr2)"""
#aggregate finctions
#sumarize data and typically return a single value
"""arr=np.array([[1,2,3,4,5],
             [6,7,8,9,10]])
print(np.sum(arr),'\n')
print(np.mean(arr))
print(np.std(arr))
print(np.var(arr))
r=np.mean(arr)
print(np.argmin(arr),'\n')
print(np.argmax(arr),'\n')
#summing the value of rows
print(np.sum(arr,axis=1))
print(np.sum(arr,axis=0))"""
#filtering = refers to the process of selecting elements from an array that match a given condition
"""ages = np.array([[21,43,53,53,63,63,73,42],
                 [53,63,64,64,63,64,34,90]])
teen =  ages[ages > 50]
print(teen)
adults = ages[(ages <= 50) & (ages >= 60)]
print(adults)

senior = ages[ages > 89]
print(senior)

odds = ages[ages % 2 != 0]
print(odds)

even = ages[ages % 2 == 0]
print(even)
#where method where any no doesnt match the condition can ba exchanged as the given value
ad = np.where(ages >=39 , ages , 'fuck u')
print(ad)

#random numbers
rng = np.random.default_rng()
print(rng.integers(48,74))
#provides random value usong built in method
print(rng.integers(48,74,43))
#provifes size of random number
print(rng.integers(low=1,high=7,size=(4, 6)))
#provides random number in dimension
#if there is a need of reproducing same results there can be udes np.random.default_rng(seed=1)
#folitng
print(np.random.uniform(-1,1,(83,92)))

#shuffling an array
rng = np.random.default_rng()
arr = np.array([1,2,3,4,5])
rng.shuffle(arr)
print(arr)
fruits = np.array(['apple','banana','orange'])
fruit =rng.choice(fruits)
print(fruit)
fruits = np.array(['apple','banana','orange'])
fruits =rng.choice(fruits,size=2)
print(fruits)
frui = np.array(['🍎','b🍌','🍊'])
frui =rng.choice(frui,size=(20,33))
print(frui)
"""












64
[64 73 58 61 51 72 66 72 70 62 64 63 57 50 67 61 66 64 51 65 61 62 69 65
 60 62 71 68 57 49 58 72 58 72 72 53 50 52 48 54 53 70 58]
[[2 6 3 2 1 6]
 [6 2 5 5 4 2]
 [5 3 4 2 1 2]
 [6 5 3 5 1 4]]
[[ 0.85430066 -0.61657399 -0.92570847 ... -0.43396732 -0.33700652
   0.76095867]
 [ 0.59562165  0.99865168  0.54529179 ...  0.07229267  0.81187747
   0.27367287]
 [-0.31480806 -0.274733   -0.7953845  ... -0.30800853  0.52027838
   0.26301381]
 ...
 [ 0.27191    -0.17494327  0.16818943 ...  0.80001794  0.57014401
  -0.01391383]
 [ 0.73987541 -0.57151061 -0.20421066 ...  0.56024729 -0.44309246
   0.82472029]
 [-0.8996875  -0.79757128  0.3830969  ... -0.16310215  0.16204025
   0.57447066]]
[3 4 1 2 5]
orange
['orange' 'orange']
[['b🍌' '🍎' '🍊' '🍊' '🍎' 'b🍌' '🍊' 'b🍌' 'b🍌' 'b🍌' '🍊' '🍎' '🍊' '🍎' '🍎' '🍊'
  '🍎' '🍎' 'b🍌' '🍎' 'b🍌' 'b🍌' '🍊' '🍊' 'b🍌' '🍊' '🍊' '🍎' '🍊' 'b🍌' '🍎' '🍊'
  '🍎']
 ['🍎' '🍊' 'b🍌' '🍎' '🍎' '🍊' '🍎' '🍊' '🍎' '🍎' '🍊' '🍎' 'b🍌' '🍎' 'b🍌' '🍊' 'b🍌'
  'b🍌' '🍎' '🍊' 'b🍌' 'b🍌' 'b🍌' '🍎' 'b🍌' '🍊' '🍊' '🍎'

In [ ]:

array1=array1*2^65
print(array1)

In [ ]:
arr = np.array([[['A','B','C'],['D','E','F'],['G','H','I']],
                [['J','K','L'],['M','N','O'],['P','Q','R']],
                [['S','T','U'],['V','W','X'],['Y','Z',' ']]])

print(arr.ndim)
print(arr.shape)







In [ ]:

word =  arr[0,1,2]+arr[2,0,2]+arr[0,0,2]+arr[1,0,1]+arr[2,2,2]+arr[2,0,2]
print(wordd)

In [ ]:
print